FROM golang:1.25.6 AS builder

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /shorter

FROM alpine:latest AS runner

COPY --from=builder /shorter app/shorter

EXPOSE 3000

CMD ["/app/shorter"]